[workspace]
resolver = "2"
members = [
#    "demo",
    "lib"
, "."]

[package]
name = "pyvector"
version = "0.1.0"
edition = "2021"

[lib]
name = "pyvector"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module", "experimental-async"] }
lib = {path = "./lib"}
tokio = { version = "1.37.0", features = ["full"] }
serde_json = "1.0.116"

[profile.release]
lto = "thin"